on:
  - push

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'

      - run: |
          yarn install --immutable --immutable-cache

      - name: Lint
        run: |
          yarn lint
          yarn tsc --noEmit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'

      - run: |
          yarn install --immutable --immutable-cache

      - name: Test
        run: |
          yarn test
